JobsFinder_Main/Controllers/GiaiThuongController.cs
using JobsFinder_Main.Common;
using JobsFinder_Main.Models;
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobsFinder_Main.Controllers
{
    public class GiaiThuongController : Controller
    {
        // GET: GiaiThuong
        public ActionResult Index()
        {
            return View();
        }

        // GET: GiaiThuong/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: GiaiThuong/Create
        [HttpPost]
        public ActionResult Create(GiaiThuongModel model)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if(session != null)
            {
                var dao = new GiaiThuongDao();

                var giaiThuong = new GiaiThuong
                {
                    TenGiaiThuong = model.TenGiaiThuong,
                    ToChuc = model.ToChuc,
                    ThangNhan = model.ThangNhan,
                    NamNhan = model.NamNhan,
                    Img = model.Img,
                    LienKet = model.LienKet,
                    UserID = session.UserID,
                    CreatedBy = session.UserName
                };

                var result = dao.Insert(giaiThuong);
                if(result == true)
                {
                    model = new GiaiThuongModel();
                    TempData["Message"] = "Cập nhật thành công!";
                    TempData["MessageType"] = "success";
                    TempData["Type"] = "Thành công";
                    return RedirectToAction("Index", "Profile", model);
                }
                else
                {
                    TempData["Message"] = "Cập nhật không thành công!";
                    TempData["MessageType"] = "error";
                    TempData["Type"] = "Thất bại";
                    return RedirectToAction("Index", "Profile");
                }
            } else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult Update(long id)
        {
            var giaiThuong = new GiaiThuongDao().ViewDetail(id);
            return PartialView(giaiThuong);
        }

        [HttpPost]
        public ActionResult Update(GiaiThuong model)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var dao = new GiaiThuongDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    if (ModelState.IsValid)
                    {
                        if (!string.IsNullOrEmpty(model.TenGiaiThuong))
                        {
                            entity.TenGiaiThuong = model.TenGiaiThuong;
                        }
                        if (!string.IsNullOrEmpty(model.ToChuc))
                        {
                            entity.ToChuc = model.ToChuc;
                        }
                        if (!string.IsNullOrEmpty(model.ThangNhan.ToString()))
                        {
                            entity.ThangNhan = model.ThangNhan;
                        }
                        if (!string.IsNullOrEmpty(model.NamNhan.ToString()))
                        {
                            entity.NamNhan = model.NamNhan;
                        }
                        entity.ModifiedBy = session.UserName;
                        entity.ModifiedDate = DateTime.Now;

                        var result = dao.Update(entity);
                        if (result)
                        {
                            TempData["Message"] = "Cập nhật thành công!";
                            TempData["MessageType"] = "success";
                            TempData["Type"] = "Thành công";
                            return RedirectToAction("Index", "Profile");
                        }
                        else
                        {
                            TempData["Message"] = "Cập nhật không thành công!";
                            TempData["MessageType"] = "error";
                            TempData["Type"] = "Thất bại";
                            return RedirectToAction("Index", "Profile");
                        }
                    }
                    else
                    {
                        TempData["Message"] = "Có lỗi xảy ra! Vui lòng thử lại!";
                        TempData["MessageType"] = "warning";
                        TempData["Type"] = "Thất bại";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "Có lỗi xảy ra! Vui lòng thử lại!";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Thất bại";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult DeleteConfirm(long id)
        {
            var giaiThuong = new GiaiThuongDao().ViewDetail(id);
            return PartialView(giaiThuong);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(GiaiThuong model)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var dao = new GiaiThuongDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    var result = dao.Delete(entity);
                    if (result)
                    {
                        TempData["Message"] = "Cập nhật thành công!";
                        TempData["MessageType"] = "success";
                        TempData["Type"] = "Thành công";
                        return RedirectToAction("Index", "Profile");
                    }
                    else
                    {
                        TempData["Message"] = "Cập nhật không thành công!";
                        TempData["MessageType"] = "error";
                        TempData["Type"] = "Thất bại";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "Có lỗi xảy ra! Vui lòng thử lại!";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Thất bại";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

JobsFinder_Main/Views/GiaiThuong/Create.cshtml
@model JobsFinder_Main.Models.GiaiThuongModel

@{
    var session = (JobsFinder_Main.Common.UserLogin)Session[JobsFinder_Main.Common.CommonConstants.USER_SESSION];
}

@if (session != null)
{
    <div id="formGiaiThuong" class="p-4 form-profile">
        @using (Html.BeginForm("Create", "GiaiThuong", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Giải thưởng</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group mb-4">
                    <p class="label-title">Tên giải thưởng</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.TenGiaiThuong, new { @class = "form-control", @placeholder = "Tên giải thưởng" })
                        @Html.ValidationMessageFor(model => model.TenGiaiThuong, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Tổ chức</p>
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ToChuc, new { @class = "form-control", @placeholder = "Tổ chức" })
                        @Html.ValidationMessageFor(model => model.ToChuc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="d-flex flex-row justify-content-between">
                    <div id="kinhNghiemnBatDau" class="d-flex justify-content-between" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Tháng nhận</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangNhan, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Chọn tháng", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ThangNhan, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Năm nhận</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        int currentYear = DateTime.Now.Year;
                                        int startYear = currentYear - 100;
                                        List<SelectListItem> years = new List<SelectListItem>();
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamNhan, years, "Chọn năm", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.NamNhan, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamNhan, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                @*<div class="form-group">
                    <p>Thêm hình ảnh hay liên kết về kinh nghiệm của bạn</p>
                    <div class="d-flex flex-row justify-content-between">
                        <div class="col-md-10" style="width:48%;">
                            @Html.TextBoxFor(model => model.Img, new { @class = "form-control" })
                            <a class="btn btn-outline-primary" id="btnChooseImage_1" style="white-space: nowrap; border-radius: 4px; margin-left: 24px; font-size: 14px; font-weight: 400; text-transform: capitalize" href="#">Tải lên</a>
                            @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-10" style="width: 48%;">
                            @Html.TextBoxFor(model => model.LienKet, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LienKet, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Hoàn tất" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    { Html.RenderAction("Login", "User"); }
}

JobsFinder_Main/Views/GiaiThuong/DeleteConfirm.cshtml
@model Model.EF.GiaiThuong

@{
    var session = (JobsFinder_Main.Common.UserLogin)Session[JobsFinder_Main.Common.CommonConstants.USER_SESSION];
}

@if (session == null)
{
    { Html.RenderAction("Login", "User"); }
}
else
{
    <div id="formDeleteGiaiThuong@(Model.ID)" class="p-4 form-profile form-delete">
        <div class="d-flex flex-column align-items-center">
            <img style="width: 120px; height: 120px; object-fit: cover;" src="~/Assets/Client/JobsFinder/img/DeleteIcon.png" />
            @using (Html.BeginForm("DeleteConfirm", "GiaiThuong", FormMethod.Post, new {@class = "box-delete"}))
            {
                @Html.AntiForgeryToken()

                <p style="font-size:  16px; font-weight: 600;">Bạn có muốn xóa mục này?</p>

                <div class="form-actions no-color d-flex justify-content-between" style="width: 100%">
                    <button type="reset" class="btn btn-outline-primary btn-cance" style="border-radius: 4px; width: 45%;">Hủy</button>
                    <button type="submit" class="btn btn-danger" style="border-radius: 4px; width: 45%;">Xóa</button>
                </div>
            }
        </div>
    </div>

    <style>
        .form-delete {
            width: 400px !important;
            margin-top: 200px !important;
        }
        .form-delete .box-delete {
            width: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
}

JobsFinder_Main/Views/GiaiThuong/Update.cshtml
@model Model.EF.GiaiThuong

@{
    var session = (JobsFinder_Main.Common.UserLogin)Session[JobsFinder_Main.Common.CommonConstants.USER_SESSION];
}

@if (session != null)
{
    <div id="formGiaiThuong@(Model.ID)" class="p-4 form-profile">
        @using (Html.BeginForm("Update", "GiaiThuong", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Giải thưởng</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group mb-4">
                    <p class="label-title">Tên giải thưởng</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.TenGiaiThuong, new { @class = "form-control", @placeholder = "Tên giải thưởng" })
                        @Html.ValidationMessageFor(model => model.TenGiaiThuong, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-4">
                    <p class="label-title">Tổ chức</p>
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ToChuc, new { @class = "form-control", @placeholder = "Tổ chức" })
                        @Html.ValidationMessageFor(model => model.ToChuc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="d-flex flex-row justify-content-between">
                    <div id="kinhNghiemnBatDau" class="d-flex justify-content-between" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Tháng nhận</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangNhan, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Chọn tháng", new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ThangNhan, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Năm nhận</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        int currentYear = DateTime.Now.Year;
                                        int startYear = currentYear - 100;
                                        List<SelectListItem> years = new List<SelectListItem>();
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamNhan, years, "Chọn năm", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.NamNhan, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamNhan, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                @*<div class="form-group">
                    <p>Thêm hình ảnh hay liên kết về kinh nghiệm của bạn</p>
                    <div class="d-flex flex-row justify-content-between">
                        <div class="col-md-10" style="width:48%;">
                            @Html.TextBoxFor(model => model.Img, new { @class = "form-control" })
                            <a class="btn btn-outline-primary" id="btnChooseImage_1" style="white-space: nowrap; border-radius: 4px; margin-left: 24px; font-size: 14px; font-weight: 400; text-transform: capitalize" href="#">Tải lên</a>
                            @Html.ValidationMessageFor(model => model.Img, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-10" style="width: 48%;">
                            @Html.TextBoxFor(model => model.LienKet, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LienKet, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Hoàn tất" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    { Html.RenderAction("Login", "User"); }
}