JobsFinder_Main/Controllers/HocVanController.cs
using JobsFinder_Main.Common;
using JobsFinder_Main.Models;
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobsFinder_Main.Controllers
{
    public class HocVanController : Controller
    {
        // GET: HocVan
        public ActionResult Index()
        {
            return View();
        }

        // GET: HocVan/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: HocVan/Create
        [HttpPost]
        public ActionResult Create(HocVanModel model)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if(session != null)
            {
                var hocvan = new HocVan();
                var dao = new HocVanDao();

                hocvan.Truong = model.Truong;
                hocvan.ChuyenNganh = model.ChuyenNganh;
                hocvan.ThangBatDau = model.ThangBatDau;
                hocvan.NamBatDau = model.NamBatDau;
                hocvan.ThangKetThuc = model.ThangKetThuc;
                hocvan.NamKetThuc = model.NamKetThuc;
                hocvan.MoTaChiTiet = model.MoTaChiTiet;
                hocvan.UserID = session.UserID;
                hocvan.CreatedBy = session.UserName;

                var result = dao.Insert(hocvan);
                if(result == true)
                {
                    TempData["Message"] = "Cập nhật thành công!";
                    TempData["MessageType"] = "success";
                    TempData["Type"] = "Thành công";
                    return RedirectToAction("Index", "Profile");
                }
                else
                {
                    TempData["Message"] = "Cập nhật không thành công!";
                    TempData["MessageType"] = "error";
                    TempData["Type"] = "Thất bại";
                    return RedirectToAction("Index", "Profile");
                }
            } else
            {
                return RedirectToAction("Login", "User");
            }
        }

        //GET: HocVan/Update/{id}
        [HttpGet]
        public ActionResult Update(long id)
        {
            var hocVan = new HocVanDao().ViewDetail(id);
            return PartialView(hocVan);
        }

        //POST: HocVan/Update/{id}
        [HttpPost]
        public ActionResult Update(HocVan model)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var dao = new HocVanDao();
                var entity = dao.ViewDetail(model.ID);
                if(entity != null)
                {
                    if (ModelState.IsValid)
                    {
                        if (!string.IsNullOrEmpty(model.Truong))
                        {
                            entity.Truong = model.Truong;
                        }
                        if (!string.IsNullOrEmpty(model.ChuyenNganh))
                        {
                            entity.ChuyenNganh = model.ChuyenNganh;
                        }
                        if (!string.IsNullOrEmpty(model.ThangBatDau.ToString()))
                        {
                            entity.ThangBatDau = model.ThangBatDau;
                        }
                        if (!string.IsNullOrEmpty(model.NamBatDau.ToString()))
                        {
                            entity.NamBatDau = model.NamBatDau;
                        }
                        if (!string.IsNullOrEmpty(model.ThangKetThuc.ToString()))
                        {
                            entity.ThangKetThuc = model.ThangKetThuc;
                        }
                        if (!string.IsNullOrEmpty(model.NamKetThuc.ToString()))
                        {
                            entity.NamKetThuc = model.NamKetThuc;
                        }
                        if (!string.IsNullOrEmpty(model.MoTaChiTiet))
                        {
                            entity.MoTaChiTiet = model.MoTaChiTiet;
                        }
                        entity.ModifiedBy = session.UserName;
                        entity.ModifiedDate = DateTime.Now;

                        var result = dao.Update(entity);
                        if (result)
                        {
                            TempData["Message"] = "Cập nhật thành công!";
                            TempData["MessageType"] = "success";
                            TempData["Type"] = "Thành công";
                            return RedirectToAction("Index", "Profile");
                        }
                        else
                        {
                            TempData["Message"] = "Cập nhật không thành công!";
                            TempData["MessageType"] = "error";
                            TempData["Type"] = "Thất bại";
                            return RedirectToAction("Index", "Profile");
                        }
                    }
                    else
                    {
                        TempData["Message"] = "Có lỗi xảy ra! Vui lòng thử lại!";
                        TempData["MessageType"] = "warning";
                        TempData["Type"] = "Thất bại";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "Có lỗi xảy ra! Vui lòng thử lại!";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Thất bại";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult DeleteConfirm(long id)
        {
            var hocVan = new HocVanDao().ViewDetail(id);
            return PartialView(hocVan);
        }

        // DELETE: HocVan/Delete/{id}
        [HttpPost]
        public ActionResult DeleteConfirm(HocVan model)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var dao = new HocVanDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    var result = dao.Delete(entity);
                    if (result)
                    {
                        TempData["Message"] = "Cập nhật thành công!";
                        TempData["MessageType"] = "success";
                        TempData["Type"] = "Thành công";
                        return RedirectToAction("Index", "Profile");
                    }
                    else
                    {
                        TempData["Message"] = "Cập nhật không thành công!";
                        TempData["MessageType"] = "error";
                        TempData["Type"] = "Thất bại";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "Có lỗi xảy ra! Vui lòng thử lại!";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Thất bại";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

JobsFinder_Main/Views/HocVan/Create.cshtml
@model JobsFinder_Main.Models.HocVanModel
@{
    var session = (JobsFinder_Main.Common.UserLogin)Session[JobsFinder_Main.Common.CommonConstants.USER_SESSION];
}

@if (session != null)
{
    <div id="formHocVan" class="p-4 form-profile">
        @using (Html.BeginForm("Create", "HocVan", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h5 class="m-0">Học vấn</h5>
                <hr class="my-3" />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group mb-4">
                    <p class="label-title">Trường</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.Truong, new { @class = "form-control", @placeholder = "Trường học" })
                        @Html.ValidationMessageFor(model => model.Truong, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <p class="label-title">Chuyên ngành</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextBoxFor(model => model.ChuyenNganh, new { @class = "form-control", @placeholder = "Công nghệ phần mềm, kinh tế, tự động hóa..." })
                        @Html.ValidationMessageFor(model => model.ChuyenNganh, "", new { @class = "text-danger" })
                    </div>
                </div>

                <label class="mb-4">
                    <input type="checkbox" id="hocVanCheckbox" class="checkbox" />
                    Tôi đang học ở đây
                </label>

                <div class="d-flex flex-row justify-content-between">
                    <div id="hocVanBatDau" class="d-flex justify-content-between" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Tháng bắt đầu</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangBatDau, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Chọn tháng", new { @class = "form-control thangBatDau" })
                                @Html.ValidationMessageFor(model => model.ThangBatDau, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Năm bắt đầu</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        int currentYear = DateTime.Now.Year;
                                        int startYear = currentYear - 100;
                                        List<SelectListItem> years = new List<SelectListItem>();
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamBatDau, years, "Chọn năm", new { @class = "form-control namBatDau" })
                                    @Html.ValidationMessageFor(model => model.NamBatDau, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamBatDau, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    
                    <div id="hocVanKetThuc" class="d-flex justify-content-between boxKetThuc" style="width: 48%">
                        <div class="form-group mb-4">
                            <p class="label-title">Tháng kết thúc</p>
                            <div class="col-md-10" style="width: 100%;">
                                @Html.DropDownListFor(model => model.ThangKetThuc, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Chọn tháng", new { @class = "form-control thangKetThuc" })
                                @Html.ValidationMessageFor(model => model.ThangKetThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group mb-4">
                            <p class="label-title">Năm kết thúc</p>
                            <div class="col-md-10" style="width: 100%;">
                                <div class="col-md-10" style="width: 100%;">
                                    @{
                                        for (int year = currentYear; year >= startYear; year--)
                                        {
                                            years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                        }
                                    }
                                    @Html.DropDownListFor(model => model.NamKetThuc, years, "Chọn năm", new { @class = "form-control namKetThuc" })
                                    @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                                </div>

                                @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <p class="label-title">Mô tả</p>
                    <div class="col-md-10" style="width: 100%;">
                        @Html.TextAreaFor(model => model.MoTaChiTiet, new{ @class = "form-control pt-2", @placeholder = "Mô tả chi tiết" })
                        @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group mb-2">
                    <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                        <input type="submit" value="Hoàn tất" class="btn btn-primary" style="border-radius: 4px;" />
                    </div>
                </div>
            </div>
        }
    </div>
} else
{
    { Html.RenderAction("Login", "User"); }
}

JobsFinder_Main/Views/HocVan/DeleteConfirm.cshtml
@model Model.EF.HocVan

@{
    var session = (JobsFinder_Main.Common.UserLogin)Session[JobsFinder_Main.Common.CommonConstants.USER_SESSION];
}

@if (session == null)
{
    { Html.RenderAction("Login", "User"); }
}
else
{
    <div id="formDeleteHocVan@(Model.ID)" class="p-4 form-profile form-delete">
        <div class="d-flex flex-column align-items-center">
            <img style="width: 120px; height: 120px; object-fit: cover;" src="~/Assets/Client/JobsFinder/img/DeleteIcon.png" />
            @using (Html.BeginForm("DeleteConfirm", "HocVan", FormMethod.Post, new {@class = "box-delete"}))
            {
                @Html.AntiForgeryToken()

                <p style="font-size:  16px; font-weight: 600;">Bạn có muốn xóa mục này?</p>

                <div class="form-actions no-color d-flex justify-content-between" style="width: 100%">
                    <button type="reset" class="btn btn-outline-primary btn-cance" style="border-radius: 4px; width: 45%;">Hủy</button>
                    <button type="submit" class="btn btn-danger" style="border-radius: 4px; width: 45%;">Xóa</button>
                </div>
            }
        </div>
    </div>

    <style>
        .form-delete {
            width: 400px !important;
            margin-top: 200px !important;
        }
        .form-delete .box-delete {
            width: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
}

JobsFinder_Main/Views/HocVan/Update.cshtml
@model Model.EF.HocVan

@{
    var session = (JobsFinder_Main.Common.UserLogin)Session[JobsFinder_Main.Common.CommonConstants.USER_SESSION];
}

@if (session == null)
{
    { Html.RenderAction("Login", "User"); }
}
else
{
    <div id="formUpdateHocVan@(Model.ID)" class="p-4 form-profile">
        @using (Html.BeginForm("Update", "Hocvan", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h5 class="m-0">Học vấn</h5>
            <hr class="my-3" />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group mb-4">
                <p class="label-title">Trường</p>
                <div class="col-md-10" style="width: 100%;">
                    @Html.TextBoxFor(model => model.Truong, new { @class = "form-control", @placeholder = "Trường học" })
                    @Html.ValidationMessageFor(model => model.Truong, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <p class="label-title">Chuyên ngành</p>
                <div class="col-md-10" style="width: 100%;">
                    @Html.TextBoxFor(model => model.ChuyenNganh, new { @class = "form-control", @placeholder = "Công nghệ phần mềm, kinh tế, tự động hóa..." })
                    @Html.ValidationMessageFor(model => model.ChuyenNganh, "", new { @class = "text-danger" })
                </div>
            </div>

            <label class="mb-4">
                <input type="checkbox" id="hocVanCheckbox" class="checkbox" />
                Tôi đang học ở đây
            </label>

            <div class="d-flex flex-row justify-content-between">
                <div id="hocVanBatDau" class="d-flex justify-content-between" style="width: 48%">
                    <div class="form-group mb-4">
                        <p class="label-title">Tháng bắt đầu</p>
                        <div class="col-md-10" style="width: 100%;">
                            @Html.DropDownListFor(model => model.ThangBatDau, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Chọn tháng", new { @class = "form-control thangBatDau" })
                            @Html.ValidationMessageFor(model => model.ThangBatDau, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-4">
                        <p class="label-title">Năm bắt đầu</p>
                        <div class="col-md-10" style="width: 100%;">
                            <div class="col-md-10" style="width: 100%;">
                                @{
                                    int currentYear = DateTime.Now.Year;
                                    int startYear = currentYear - 100;
                                    List<SelectListItem> years = new List<SelectListItem>();
                                    for (int year = currentYear; year >= startYear; year--)
                                    {
                                        years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                    }
                                }
                                @Html.DropDownListFor(model => model.NamBatDau, years, "Chọn năm", new { @class = "form-control namBatDau" })
                                @Html.ValidationMessageFor(model => model.NamBatDau, "", new { @class = "text-danger" })
                            </div>

                            @Html.ValidationMessageFor(model => model.NamBatDau, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div id="hocVanKetThuc" class="d-flex justify-content-between boxKetThuc" style="width: 48%">
                    <div class="form-group mb-4">
                        <p class="label-title">Tháng kết thúc</p>
                        <div class="col-md-10" style="width: 100%;">
                            @Html.DropDownListFor(model => model.ThangKetThuc, Enumerable.Range(1, 12).Select(i => new SelectListItem { Value = i.ToString(), Text = i.ToString() }), "Chọn tháng", new { @class = "form-control thangKetThuc" })
                            @Html.ValidationMessageFor(model => model.ThangKetThuc, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-4">
                        <p class="label-title">Năm kết thúc</p>
                        <div class="col-md-10" style="width: 100%;">
                            <div class="col-md-10" style="width: 100%;">
                                @{
                                    for (int year = currentYear; year >= startYear; year--)
                                    {
                                        years.Add(new SelectListItem { Value = year.ToString(), Text = year.ToString() });
                                    }
                                }
                                @Html.DropDownListFor(model => model.NamKetThuc, years, "Chọn năm", new { @class = "form-control namKetThuc" })
                                @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                            </div>

                            @Html.ValidationMessageFor(model => model.NamKetThuc, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <p class="label-title">Mô tả</p>
                <div class="col-md-10" style="width: 100%;">
                    @Html.TextAreaFor(model => model.MoTaChiTiet, new { @class = "form-control pt-2", @placeholder = "Mô tả chi tiết" })
                    @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mb-2">
                <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                    <input type="submit" value="Hoàn tất" class="btn btn-primary" style="border-radius: 4px;" />
                </div>
            </div>
        </div>
        }
    </div>
}