JobsFinder_Main/Controllers/KyNangController.cs
using JobsFinder_Main.Common;
using JobsFinder_Main.Models;
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobsFinder_Main.Controllers
{
    public class KyNangController : Controller
    {
        // GET: KyNang
        public ActionResult Index()
        {
            return View();
        }

        // GET: KyNang/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: KyNang/Create
        [HttpPost]
        public ActionResult Create(KyNangModel model)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if(session != null)
            {
                var dao = new KyNangDao();

                var kyNang = new KyNang
                {
                    TenKyNang = model.TenKyNang,
                    DanhGia = model.DanhGia,
                    MoTaChiTiet = model.MoTaChiTiet,
                    UserID = session.UserID,
                    CreatedBy = session.UserName
                };

                var result = dao.Insert(kyNang);
                if(result == true)
                {
                    model = new KyNangModel();
                    TempData["Message"] = "Cập nhật thành công!";
                    TempData["MessageType"] = "success";
                    TempData["Type"] = "Thành công";
                    return RedirectToAction("Index", "Profile", model);
                }
                else
                {
                    TempData["Message"] = "Cập nhật không thành công!";
                    TempData["MessageType"] = "error";
                    TempData["Type"] = "Thất bại";
                    return RedirectToAction("Index", "Profile");
                }
            } else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult Update(long id)
        {
            var kyNang = new KyNangDao().ViewDetail(id);
            return PartialView(kyNang);
        }

        [HttpPost]
        public ActionResult Update(KyNang model)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var dao = new KyNangDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    if (ModelState.IsValid)
                    {
                        if (!string.IsNullOrEmpty(model.TenKyNang))
                        {
                            entity.TenKyNang = model.TenKyNang;
                        }
                        if (!string.IsNullOrEmpty(model.DanhGia.ToString()))
                        {
                            entity.DanhGia = model.DanhGia;
                        }
                        if (!string.IsNullOrEmpty(model.MoTaChiTiet))
                        {
                            entity.MoTaChiTiet = model.MoTaChiTiet;
                        }
                        entity.ModifiedBy = session.UserName;
                        entity.ModifiedDate = DateTime.Now;

                        var result = dao.Update(entity);
                        if (result)
                        {
                            TempData["Message"] = "Cập nhật thành công!";
                            TempData["MessageType"] = "success";
                            TempData["Type"] = "Thành công";
                            return RedirectToAction("Index", "Profile");
                        }
                        else
                        {
                            TempData["Message"] = "Cập nhật không thành công!";
                            TempData["MessageType"] = "error";
                            TempData["Type"] = "Thất bại";
                            return RedirectToAction("Index", "Profile");
                        }
                    }
                    else
                    {
                        TempData["Message"] = "Có lỗi xảy ra! Vui lòng thử lại!";
                        TempData["MessageType"] = "warning";
                        TempData["Type"] = "Thất bại";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "Có lỗi xảy ra! Vui lòng thử lại!";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Thất bại";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpGet]
        public ActionResult DeleteConfirm(long id)
        {
            var kyNang = new KyNangDao().ViewDetail(id);
            return PartialView(kyNang);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(KyNang model)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (session != null)
            {
                var dao = new KyNangDao();
                var entity = dao.ViewDetail(model.ID);
                if (entity != null)
                {
                    var result = dao.Delete(entity);
                    if (result)
                    {
                        TempData["Message"] = "Cập nhật thành công!";
                        TempData["MessageType"] = "success";
                        TempData["Type"] = "Thành công";
                        return RedirectToAction("Index", "Profile");
                    }
                    else
                    {
                        TempData["Message"] = "Cập nhật không thành công!";
                        TempData["MessageType"] = "error";
                        TempData["Type"] = "Thất bại";
                        return RedirectToAction("Index", "Profile");
                    }
                }
                else
                {
                    TempData["Message"] = "Có lỗi xảy ra! Vui lòng thử lại!";
                    TempData["MessageType"] = "warning";
                    TempData["Type"] = "Thất bại";
                    return RedirectToAction("Index", "Profile");
                }
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

JobsFinder_Main/Views/KyNang/Create.cshtml
@model JobsFinder_Main.Models.KyNangModel

@{
    var session = (JobsFinder_Main.Common.UserLogin)Session[JobsFinder_Main.Common.CommonConstants.USER_SESSION];
}

@if (session != null)
{
<div id="formKyNang" class="p-4 form-profile">
    @using (Html.BeginForm("Create", "KyNang", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h5 class="m-0">Kỹ năng</h5>
            <hr class="my-3" />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group mb-4">
                <p class="label-title">Tên kỹ năng</p>
                <div class="col-md-10" style="width: 100%;">
                    @Html.TextBoxFor(model => model.TenKyNang, new { @class = "form-control", @placeholder = "Nhập tên kỹ năng" })
                    @Html.ValidationMessageFor(model => model.TenKyNang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mb-4">
                <p class="label-title">Đánh giá</p>
                <div class="col-md-10" style="width: 100%;">
                    @Html.TextBoxFor(model => model.DanhGia, new { @class = "form-control", @type ="hidden" })
                    @Html.ValidationMessageFor(model => model.DanhGia, "", new { @class = "text-danger" })
                </div>
                <div class="box-rating d-flex flex-row">
                    <i class="bi bi-star"></i>
                    <i class="bi bi-star"></i>
                    <i class="bi bi-star"></i>
                    <i class="bi bi-star"></i>
                    <i class="bi bi-star"></i>
                </div>
                <p class="rating-caption" style="height: 26px;">Chọn số sao tương ứng với mức độ kỹ năng của bạn</p>
            </div>

            <style>
                .box-rating i {
                    font-size: 20px;
                    padding: 4px;
                    margin-right: 8px;
                }
                .box-rating i.bi-star-fill {
                    color: gold;
                }
            </style>

            <script>
                var stars = document.querySelectorAll(".bi-star");
                var inputDanhGia = document.getElementById("DanhGia");
                var ratingCaption = document.querySelector(".rating-caption");

                var captions = [
                    "Chỉ mới nghe qua",
                    "Chưa có sản phẩm hoàn chỉnh",
                    "Có sản phẩm hoàn chỉnh",
                    "Có sản phẩm hoàn chỉnh trên cùng một nhóm",
                    "Thành thạo"
                ];

                stars.forEach(function (star, index) {
                    star.addEventListener("click", function () {
                        var rating = index + 1;
                        inputDanhGia.value = rating;
                        updateStars();
                        ratingCaption.textContent = captions[rating - 1];
                    });

                    star.addEventListener("mouseover", function () {
                        for (var i = 0; i <= index; i++) {
                            stars[i].classList.remove("bi-star");
                            stars[i].classList.add("bi-star-fill");
                        }

                        for (var j = index + 1; j < stars.length; j++) {
                            stars[j].classList.add("bi-star");
                            stars[j].classList.remove("bi-star-fill");
                        }
                        ratingCaption.textContent = captions[index];
                    });

                    star.addEventListener("mouseout", function () {
                        updateStars();
                        var rating = parseInt(inputDanhGia.value);
                        ratingCaption.textContent = captions[rating - 1];
                    });
                });

                function updateStars() {
                    stars.forEach(function (star, index) {
                        star.classList.remove("bi-star-fill");
                        star.classList.add("bi-star");
                    });

                    var rating = parseInt(inputDanhGia.value);
                    for (var i = 0; i < rating; i++) {
                        stars[i].classList.remove("bi-star");
                        stars[i].classList.add("bi-star-fill");
                    }
                }
            </script>

            <div class="form-group">
                <p class="label-title">Mô tả</p>
                <div class="col-md-10" style="width: 100%;">
                    @Html.TextAreaFor(model => model.MoTaChiTiet, new { @class = "form-control pt-2", @placeholder = "Mô tả chi tiết" })
                    @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mb-2">
                <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                    <input type="submit" value="Hoàn tất" class="btn btn-primary" style="border-radius: 4px;" />
                </div>
            </div>
        </div>
    }
</div>
}
else
{
    { Html.RenderAction("Login", "User"); }
}

JobsFinder_Main/Views/KyNang/DeleteConfirm.cshtml
@model Model.EF.KyNang

@{
    var session = (JobsFinder_Main.Common.UserLogin)Session[JobsFinder_Main.Common.CommonConstants.USER_SESSION];
}

@if (session == null)
{
    { Html.RenderAction("Login", "User"); }
}
else
{
    <div id="formDeleteKyNang@(Model.ID)" class="p-4 form-profile form-delete">
        <div class="d-flex flex-column align-items-center">
            <img style="width: 120px; height: 120px; object-fit: cover;" src="~/Assets/Client/JobsFinder/img/DeleteIcon.png" />
            @using (Html.BeginForm("DeleteConfirm", "KyNang", FormMethod.Post, new {@class = "box-delete"}))
            {
                @Html.AntiForgeryToken()

                <p style="font-size:  16px; font-weight: 600;">Bạn có muốn xóa mục này?</p>

                <div class="form-actions no-color d-flex justify-content-between" style="width: 100%">
                    <button type="reset" class="btn btn-outline-primary btn-cance" style="border-radius: 4px; width: 45%;">Hủy</button>
                    <button type="submit" class="btn btn-danger" style="border-radius: 4px; width: 45%;">Xóa</button>
                </div>
            }
        </div>
    </div>

    <style>
        .form-delete {
            width: 400px !important;
            margin-top: 200px !important;
        }
        .form-delete .box-delete {
            width: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
}

JobsFinder_Main/Views/KyNang/Update.cshtml
@model Model.EF.KyNang

@{
    var session = (JobsFinder_Main.Common.UserLogin)Session[JobsFinder_Main.Common.CommonConstants.USER_SESSION];
}

@if (session != null)
{
<div id="formKyNang@(Model.ID)" class="p-4 form-profile">
    @using (Html.BeginForm("Update", "KyNang", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h5 class="m-0">Kỹ năng</h5>
            <hr class="my-3" />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group mb-4">
                <p class="label-title">Tên kỹ năng</p>
                <div class="col-md-10" style="width: 100%;">
                    @Html.TextBoxFor(model => model.TenKyNang, new { @class = "form-control", @placeholder = "Nhập tên kỹ năng" })
                    @Html.ValidationMessageFor(model => model.TenKyNang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mb-4">
                <p class="label-title">Đánh giá</p>
                <div class="col-md-10" style="width: 100%;">
                    @Html.TextBoxFor(model => model.DanhGia, new { @class = "form-control", @type ="hidden" })
                    @Html.ValidationMessageFor(model => model.DanhGia, "", new { @class = "text-danger" })
                </div>
                <div class="box-rating d-flex flex-row">
                    <i class="bi bi-star"></i>
                    <i class="bi bi-star"></i>
                    <i class="bi bi-star"></i>
                    <i class="bi bi-star"></i>
                    <i class="bi bi-star"></i>
                </div>
                <p class="rating-caption" style="height: 26px;">Chọn số sao tương ứng với mức độ kỹ năng của bạn</p>
            </div>

            <style>
                .box-rating i {
                    font-size: 20px;
                    padding: 4px;
                    margin-right: 8px;
                }
                .box-rating i.bi-star-fill {
                    color: gold;
                }
            </style>

            <script>
                var stars = document.querySelectorAll(".bi-star");
                var inputDanhGia = document.getElementById("DanhGia");
                var ratingCaption = document.querySelector(".rating-caption");

                var captions = [
                    "Chỉ mới nghe qua",
                    "Chưa có sản phẩm hoàn chỉnh",
                    "Có sản phẩm hoàn chỉnh",
                    "Có sản phẩm hoàn chỉnh trên cùng một nhóm",
                    "Thành thạo"
                ];

                stars.forEach(function (star, index) {
                    star.addEventListener("click", function () {
                        var rating = index + 1;
                        inputDanhGia.value = rating;
                        updateStars();
                        ratingCaption.textContent = captions[rating - 1];
                    });

                    star.addEventListener("mouseover", function () {
                        for (var i = 0; i <= index; i++) {
                            stars[i].classList.remove("bi-star");
                            stars[i].classList.add("bi-star-fill");
                        }

                        for (var j = index + 1; j < stars.length; j++) {
                            stars[j].classList.add("bi-star");
                            stars[j].classList.remove("bi-star-fill");
                        }
                        ratingCaption.textContent = captions[index];
                    });

                    star.addEventListener("mouseout", function () {
                        updateStars();
                        var rating = parseInt(inputDanhGia.value);
                        ratingCaption.textContent = captions[rating - 1];
                    });
                });

                function updateStars() {
                    stars.forEach(function (star, index) {
                        star.classList.remove("bi-star-fill");
                        star.classList.add("bi-star");
                    });

                    var rating = parseInt(inputDanhGia.value);
                    for (var i = 0; i < rating; i++) {
                        stars[i].classList.remove("bi-star");
                        stars[i].classList.add("bi-star-fill");
                    }
                }
            </script>

            <div class="form-group">
                <p class="label-title">Mô tả</p>
                <div class="col-md-10" style="width: 100%;">
                    @Html.TextAreaFor(model => model.MoTaChiTiet, new { @class = "form-control pt-2", @placeholder = "Mô tả chi tiết" })
                    @Html.ValidationMessageFor(model => model.MoTaChiTiet, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mb-2">
                <div class="col-md-offset-2 col-md-10 d-flex justify-content-center" style="width: 100%">
                    <input type="submit" value="Hoàn tất" class="btn btn-primary" style="border-radius: 4px;" />
                </div>
            </div>
        </div>
    }
</div>
}
else
{
    { Html.RenderAction("Login", "User"); }
}